set TARGET_DIR=R:\simutrans\pak


@del %TARGET_DIR%\bridge.ClassicRail.pak
@del %TARGET_DIR%\bridge.ClassicRoad.pak
@del %TARGET_DIR%\bridge.MaglevBridge.pak
@del %TARGET_DIR%\bridge.ModernRoad.pak
@del %TARGET_DIR%\bridge.MonorailRamp.pak
@del %TARGET_DIR%\bridge.PowerBridge.pak
@del %TARGET_DIR%\bridge.Schiffhebewerk.pak
@del %TARGET_DIR%\bridge.SteelRail.pak
@del %TARGET_DIR%\bridge.ViaductRail.pak
@del %TARGET_DIR%\bridge.WoodenRoad.pak
@del %TARGET_DIR%\bridge.koka_Bridge_single.pak
@del %TARGET_DIR%\bridge.mlm_concrete_bridge.pak
@del %TARGET_DIR%\bridge.tb_classic_road.pak
@del %TARGET_DIR%\building.00_01_CITY.pak
@del %TARGET_DIR%\building.01_CITY.pak
@del %TARGET_DIR%\building.02_CITY.pak
@del %TARGET_DIR%\building.03_CITY.pak
@del %TARGET_DIR%\building.03_CITY_A.pak
@del %TARGET_DIR%\building.03_CITY_B.pak
@del %TARGET_DIR%\building.03_CITY_C.pak
@del %TARGET_DIR%\building.04_CITY.pak
@del %TARGET_DIR%\building.04_CITY_A.pak
@del %TARGET_DIR%\building.04_CITY_B.pak
@del %TARGET_DIR%\building.04_CITY_C.pak
@del %TARGET_DIR%\building.10_WOHN.pak
@del %TARGET_DIR%\building.1930AirDepot.pak
@del %TARGET_DIR%\building.1headquarter.pak
@del %TARGET_DIR%\building.2headquarter.pak
@del %TARGET_DIR%\building.3headquarter.pak
@del %TARGET_DIR%\building.4headquarter.pak
@del %TARGET_DIR%\building.5headquarter.pak
@del %TARGET_DIR%\building.A1_ALTE_KIRCHE.pak
@del %TARGET_DIR%\building.A2_SCHLOSS1.pak
@del %TARGET_DIR%\building.A3_BURG1.pak
@del %TARGET_DIR%\building.A4_SCHLOSS2.pak
@del %TARGET_DIR%\building.A5_STONEHENGE.pak
@del %TARGET_DIR%\building.A6_DOME.pak
@del %TARGET_DIR%\building.AirDepot.pak
@del %TARGET_DIR%\building.AirStop.pak
@del %TARGET_DIR%\building.AirTerminal477.pak
@del %TARGET_DIR%\building.AirportShed1930.pak
@del %TARGET_DIR%\building.Avila_Big_StationBlg.pak
@del %TARGET_DIR%\building.Avila_Small_StationBlg.pak
@del %TARGET_DIR%\building.Avila_Warehouse_StationBlg.pak
@del %TARGET_DIR%\building.BigPostOffice.pak
@del %TARGET_DIR%\building.BigTerminal477.pak
@del %TARGET_DIR%\building.Bulk_StationBlg.pak
@del %TARGET_DIR%\building.BusStop.pak
@del %TARGET_DIR%\building.CarDepot.pak
@del %TARGET_DIR%\building.CarStop.pak
@del %TARGET_DIR%\building.Car_StationBlg.pak
@del %TARGET_DIR%\building.CattlePorch.pak
@del %TARGET_DIR%\building.ChannelStop.pak
@del %TARGET_DIR%\building.Control_StationBlg.pak
@del %TARGET_DIR%\building.Denk*.pak
@del %TARGET_DIR%\building.Eingang.pak
@del %TARGET_DIR%\building.Feste.pak
@del %TARGET_DIR%\building.Fluid_StationBlg.pak
@del %TARGET_DIR%\building.FreightShipStop.pak
@del %TARGET_DIR%\building.FreightTrainStop.pak
@del %TARGET_DIR%\building.GCG1TrainStop.pak
@del %TARGET_DIR%\building.GCG2TrainStop.pak
@del %TARGET_DIR%\building.GCGTrainStop.pak
@del %TARGET_DIR%\building.Gas_StationBlg.pak
@del %TARGET_DIR%\building.Goods_StationBlg.pak
@del %TARGET_DIR%\building.Gymnasium.pak
@del %TARGET_DIR%\building.HallBusStop.pak
@del %TARGET_DIR%\building.KingsbridgeMonastry.pak
@del %TARGET_DIR%\building.LargeShipStop.pak
@del %TARGET_DIR%\building.LeuchtturmShipStop.pak
@del %TARGET_DIR%\building.Lighthouse.pak
@del %TARGET_DIR%\building.LongBusStop.pak
@del %TARGET_DIR%\building.MHzSmallStation.pak
@del %TARGET_DIR%\building.MainTerminal1930.pak
@del %TARGET_DIR%\building.ModernAirTerminal477.pak
@del %TARGET_DIR%\building.MonorailDepot.pak
@del %TARGET_DIR%\building.MonorailFoundation.pak
@del %TARGET_DIR%\building.MonorailGround.pak
@del %TARGET_DIR%\building.OldTownhall.pak
@del %TARGET_DIR%\building.PSFreightTrainStop.pak
@del %TARGET_DIR%\building.PSHall1TrainStop.pak
@del %TARGET_DIR%\building.PSHall2TrainStop.pak
@del %TARGET_DIR%\building.Patricks_Rock.pak
@del %TARGET_DIR%\building.PlainAirStop.pak
@del %TARGET_DIR%\building.PostOffice.pak
@del %TARGET_DIR%\building.PostStop.pak
@del %TARGET_DIR%\building.RUIN_0.pak
@del %TARGET_DIR%\building.Raven_Kirche.pak
@del %TARGET_DIR%\building.STADIUM2.pak
@del %TARGET_DIR%\building.SandStationMHz.pak
@del %TARGET_DIR%\building.ShipDepot.pak
@del %TARGET_DIR%\building.ShipDepotEW.pak
@del %TARGET_DIR%\building.ShipStop.pak
@del %TARGET_DIR%\building.Tennis_Court.pak
@del %TARGET_DIR%\building.Terminal1930.pak
@del %TARGET_DIR%\building.Theatre.pak
@del %TARGET_DIR%\building.Tower1930.pak
@del %TARGET_DIR%\building.TowerMoistboy.pak
@del %TARGET_DIR%\building.TrainDepot.pak
@del %TARGET_DIR%\building.TrainStop.pak
@del %TARGET_DIR%\building.TrainStopMaglev.pak
@del %TARGET_DIR%\building.TrainStopMaglevIndicator.pak
@del %TARGET_DIR%\building.TramDepot.pak
@del %TARGET_DIR%\building.VictorianStation.pak
@del %TARGET_DIR%\building.Vorplatz.pak
@del %TARGET_DIR%\building.Windmill.pak
@del %TARGET_DIR%\building.com*.pak
@del %TARGET_DIR%\building.ind*.pak
@del %TARGET_DIR%\building.leftShipStop.pak
@del %TARGET_DIR%\building.rampShipStop.pak
@del %TARGET_DIR%\building.res*.pak
@del %TARGET_DIR%\building.rightShipStop.pak
@del %TARGET_DIR%\crossing.rail-road-crossing.pak
@del %TARGET_DIR%\crossing.rail-road-crossing_new.pak
@del %TARGET_DIR%\factory.2Raffinerie.pak
@del %TARGET_DIR%\factory.3Raffinerie.pak
@del %TARGET_DIR%\factory.Aufwindkraftwerk.pak
@del %TARGET_DIR%\factory.Autohaus.pak
@del %TARGET_DIR%\factory.Autohersteller.pak
@del %TARGET_DIR%\factory.Buchgrosshandel.pak
@del %TARGET_DIR%\factory.CHEMIST.pak
@del %TARGET_DIR%\factory.Cementmill.pak
@del %TARGET_DIR%\factory.ChemicalPlant.pak
@del %TARGET_DIR%\factory.Concretefactory.pak
@del %TARGET_DIR%\factory.Druckerei.pak
@del %TARGET_DIR%\factory.Erzbergwerk.pak
@del %TARGET_DIR%\factory.Geokraftwerk.pak
@del %TARGET_DIR%\factory.Incinerator.pak
@del %TARGET_DIR%\factory.Kohlegrube.pak
@del %TARGET_DIR%\factory.Kohlekraftwerk.pak
@del %TARGET_DIR%\factory.Marketplace.pak
@del %TARGET_DIR%\factory.Materialswholesale.pak
@del %TARGET_DIR%\factory.Moebelfabrik.pak
@del %TARGET_DIR%\factory.Moebelhaus.pak
@del %TARGET_DIR%\factory.Muellkraftwerk.pak
@del %TARGET_DIR%\factory.Nutzwald.pak
@del %TARGET_DIR%\factory.Oelbohrinsel.pak
@del %TARGET_DIR%\factory.Oelfeld.pak
@del %TARGET_DIR%\factory.Oelkraftwerk.pak
@del %TARGET_DIR%\factory.Oelpumpe.pak
@del %TARGET_DIR%\factory.Papierfabrik.pak
@del %TARGET_DIR%\factory.Pharmaceutics.pak
@del %TARGET_DIR%\factory.Raffinerie.pak
@del %TARGET_DIR%\factory.Rinnenkraftwerk.pak
@del %TARGET_DIR%\factory.Saegewerk.pak
@del %TARGET_DIR%\factory.SaegewerkMHz.pak
@del %TARGET_DIR%\factory.Sandquarry.pak
@del %TARGET_DIR%\factory.Stahlwerk.pak
@del %TARGET_DIR%\factory.Stonequarry.pak
@del %TARGET_DIR%\factory.TANKE.pak
@del %TARGET_DIR%\factory.Turmkraftwerk.pak
@del %TARGET_DIR%\factory.Windkraftwerk.pak
@del %TARGET_DIR%\factory.bakery.pak
@del %TARGET_DIR%\factory.brewery.pak
@del %TARGET_DIR%\factory.cannery.pak
@del %TARGET_DIR%\factory.cow_farm.pak
@del %TARGET_DIR%\factory.dairy.pak
@del %TARGET_DIR%\factory.fish_pond.pak
@del %TARGET_DIR%\factory.fish_swarm.pak
@del %TARGET_DIR%\factory.food_processing_plant.pak
@del %TARGET_DIR%\factory.grain_farm.pak
@del %TARGET_DIR%\factory.grain_mill.pak
@del %TARGET_DIR%\factory.grain_windmill.pak
@del %TARGET_DIR%\factory.old_farm.pak
@del %TARGET_DIR%\factory.scrap_yard.pak
@del %TARGET_DIR%\factory.supermarket.pak
@del %TARGET_DIR%\factory.thermisches_Solarkraftwerk.pak
@del %TARGET_DIR%\field.cow_fields.pak
@del %TARGET_DIR%\field.wheat_fields.pak
@del %TARGET_DIR%\ground.Basement.pak
@del %TARGET_DIR%\ground.Borders.pak
@del %TARGET_DIR%\ground.ClimateTexture.pak
@del %TARGET_DIR%\ground.Fence.pak
@del %TARGET_DIR%\ground.LightTexture.pak
@del %TARGET_DIR%\ground.Marker.pak
@del %TARGET_DIR%\ground.Outside.pak
@del %TARGET_DIR%\ground.ShoreTrans.pak
@del %TARGET_DIR%\ground.SlopeTrans.pak
@del %TARGET_DIR%\ground.Slopes.pak
@del %TARGET_DIR%\ground.Water.pak
@del %TARGET_DIR%\ground_obj.Hochsitz1.pak
@del %TARGET_DIR%\ground_obj.Hochsitz2.pak
@del %TARGET_DIR%\ground_obj.gemsen.pak
@del %TARGET_DIR%\ground_obj.gooses.pak
@del %TARGET_DIR%\ground_obj.sheeps.pak
@del %TARGET_DIR%\misc.Construction.pak
@del %TARGET_DIR%\misc.PowerDest.pak
@del %TARGET_DIR%\misc.PowerSource.pak
@del %TARGET_DIR%\misc.Sidewalk.pak
@del %TARGET_DIR%\pedestrian.*.pak
@del %TARGET_DIR%\roadsign.choose_point.pak
@del %TARGET_DIR%\roadsign.ChooseSignals.pak
@del %TARGET_DIR%\roadsign.ChooseSignalsMonorail.pak
@del %TARGET_DIR%\roadsign.Endofchoosetrack.pak
@del %TARGET_DIR%\roadsign.GreedyBlockSignals.pak
@del %TARGET_DIR%\roadsign.LongBlockSignals.pak
@del %TARGET_DIR%\roadsign.RailClose.pak
@del %TARGET_DIR%\roadsign.Railgate.pak
@del %TARGET_DIR%\roadsign.Signals.pak
@del %TARGET_DIR%\roadsign.SignalsMonorail.pak
@del %TARGET_DIR%\roadsign.preSignals.pak
@del %TARGET_DIR%\roadsign.preSignalsMonorail.pak
@del %TARGET_DIR%\roadsign.traffic_light.pak
@del %TARGET_DIR%\symbol.CompassIso.pak
@del %TARGET_DIR%\symbol.CompassMap.pak
@del %TARGET_DIR%\tree.*.pak
@del %TARGET_DIR%\tunnel.FastRailTunnel.pak
@del %TARGET_DIR%\tunnel.FastRoadTunnel.pak
@del %TARGET_DIR%\tunnel.PowerTunnel.pak
@del %TARGET_DIR%\tunnel.RailTunnel.pak
@del %TARGET_DIR%\tunnel.RoadTunnel.pak
@REM @del %TARGET_DIR%\vehicle.*.pak
@del %TARGET_DIR%\vehicle.JumboCruiser.pak
@del %TARGET_DIR%\vehicle.JumboCruiserBack1.pak
@del %TARGET_DIR%\vehicle.JumboCruiserBack2.pak
@del %TARGET_DIR%\vehicle.Turgot.pak
@del %TARGET_DIR%\vehicle.Viggen.pak
@del %TARGET_DIR%\vehicle.schooner.pak
@del %TARGET_DIR%\vehicle.teaclipper.pak
@del %TARGET_DIR%\way-object.HighSpeedOverheadpower.pak
@del %TARGET_DIR%\way-object.SlowOverheadpower.pak
@del %TARGET_DIR%\way.Kanal.pak
@del %TARGET_DIR%\way.MaglevTrack.pak
@del %TARGET_DIR%\way.MaglevTrackElevated.pak
@del %TARGET_DIR%\way.Powerline.pak
@del %TARGET_DIR%\way.Rillenschienen.pak
@del %TARGET_DIR%\way.asphalt_road.pak
@del %TARGET_DIR%\way.city_road.pak
@del %TARGET_DIR%\way.cobblestone_road.pak
@del %TARGET_DIR%\way.concrete_sleeper_track.pak
@del %TARGET_DIR%\way.dirt_road.pak
@del %TARGET_DIR%\way.elevated_monorail.pak
@del %TARGET_DIR%\way.gavel_road.pak
@del %TARGET_DIR%\way.mip_cobblestone_road.pak
@del %TARGET_DIR%\way.monorail.pak
@del %TARGET_DIR%\way.river.pak
@del %TARGET_DIR%\way.river2.pak
@del %TARGET_DIR%\way.runway_grass.pak
@del %TARGET_DIR%\way.runway_modern.pak
@del %TARGET_DIR%\way.sand_track.pak
@del %TARGET_DIR%\way.steel_sleeper_track.pak
@del %TARGET_DIR%\way.taxiway.pak
@del %TARGET_DIR%\way.wooden_sleeper_track.pak


@del %TARGET_DIR%\compat.tab
@del %TARGET_DIR%\text\*.tab
@del %TARGET_DIR%\text\citylist_*.txt
@del %TARGET_DIR%\config\alternative_cityrules.tab
for /D %%1 in (%TARGET_DIR%\scenario\*) do @rmdir /S /Q %%1

copy .\*.pak %TARGET_DIR%
copy .\compat.tab %TARGET_DIR%
copy .\config %TARGET_DIR%\config
copy .\text %TARGET_DIR%\text
mkdir %TARGET_DIR%\license
copy .\license %TARGET_DIR%\license

ren %TARGET_DIR% pak.nippon